name: street_pizza
favicon: null
layout_spectrum: 0.4263372803106904
typography_spectrum: 0.4195247832685709
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8230476197786629
  lightness: 0.5967529404442757
  saturation: 0.4727081584278494
  rhythmicContrast: 0.8505128570832312
purpose: []
